### PR TITLE
Add srht .build.yml for CI

### PR DESCRIPTION
**Pull request by MaxLeiter**
example build: https://builds.sr.ht/~maxleiter/job/8925

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Can you base this off of Alpine? We'd get faster builds.

**Comment by MaxLeiter** [comment]
Done

**Comment by SirCmpwn** [comment]
Thanks, I'll merge this once github figures their shit out.

**Comment by SirCmpwn** [comment]
Thanks!

**Pull request merged**
